# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Redline.FM
tagline:          'A Formula 1 podcast discussing Formula 1 and other forms of racing'
description:      'Hosts <a href="http://www.twitter.com/brian_williams" target="_blank">Brian Williams</a> and <a href="https://twitter.com/burnedpixel" target="_blank">Chris Chernoff</a> discuss the pinnacle of motor racing: Formula 1'
url:              http://www.redline.fm

author:
  name:           'Chris Chernoff'
  url:            https://twitter.com/burnedpixel	

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/redlinefm/redlinefm

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
