# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Redline.FM
tagline:          'A podcast discussing Formula 1 and all things racing.'
description:      '<a href="https://twitter.com/burnedpixel" target="_blank">Chris Chernoff</a> and <a href="http://www.twitter.com/brian_williams" target="_blank">Brian Williams</a> offer their thoughts on the teams, drivers, tech, and latest news for each Formula 1 race.'
feed_description: 'Hosts Chris Chernoff and Brian Williams offer their thoughts on the teams, drivers, tech, and latest news for each Formula 1 race.'

url:              http://www.redline.fm/
keywords:		  'F1, Formula 1, Formula One, Racing'

author:
  name:           'Chris Chernoff'
  email:		  chris@burnedpixel.com
  url:            https://twitter.com/burnedpixel	

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/redlinefm/redlinefm

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
