# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Redline.FM
tagline:          'A podcast discussing Formula 1 and all things racing.'
description:      'Featuring <a href="http://www.twitter.com/brian_williams" target="_blank">Brian Williams</a> and <a href="https://twitter.com/burnedpixel" target="_blank">Chris Chernoff</a>'
url:              http://www.redline.fm/

author:
  name:           'Chris Chernoff'
  email:		  chris@burnedpixel.com
  url:            https://twitter.com/burnedpixel	

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/redlinefm/redlinefm

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
